#spring.application.name=music-resource-management

server:
  port: 8085

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/musicresourcessystem?serverTimezone=UTC
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true  # 格式化 SQL（可选）
        dialect: org.hibernate.dialect.MySQL8Dialect  # 明确指定方言（可选）


mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.g12.entity
  configuration:
    #??????
    map-underscore-to-camel-case: true


logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info